"""Record CPython's results for version-specific syntax as Rust tests.

Usage: run once with each of python3.12, python3.13 and python3.14:
    python3.X scripts/gen_version_cases.py rust/crates/parser/tests/versions

Each run writes cases_3X.rs: for every source below, CPython's ast.dump
(with positions), its compile() outcome and its symbol table dump, in the
formats of scripts/parser_parity.py, compile_parity.py and
symtable_parity.py. rust/crates/parser/tests/versions.rs compares the
parser's output for that Python version with them. Nothing is executed.
"""

import ast
from pathlib import Path
import symtable
import sys
import warnings

SOURCES_TUPLE = (
    "def first[T = int](items: list[T]) -> T:\n    return items[0]\n",
    "class Box[*Ts = *tuple[int], **P = [int]]:\n    pass\n",
    "type Pair[T: (int, str) = int] = tuple[T, T]\n",
    "value = f'{x:{w}}' f'{y:>{w}.{p}}'\n",
    "value = f'{x:\n}'\n",
    "name = 'x'\nmessage = t'hello {name!r:>{width}} {count=}'\n",
    "message = t'a' t'{b}' T'c{d}'\n",
    "message = t'a' 'b'\n",
    "data = ub'x'\n",
    "try:\n    pass\nexcept ValueError, TypeError:\n    pass\n",
    "try:\n    pass\nexcept* ValueError, TypeError:\n    pass\n",
    "try:\n    pass\nexcept ValueError, TypeError as error:\n    pass\n",
    "try:\n    pass\nexcept ValueError as error.attribute:\n    pass\n",
    "count: int = 1\nif count:\n    other: str = 'a'\n",
    "class C:\n    size: int = 1\n    if size:\n        name: str\n",
    "def f(a: int, *b: str, c: 'C' = 1, **d: bytes) -> float:\n"
    "    local: list[int] = []\n    return 1.0\n",
    "value: (y := 1) = 2\n",
    "def f():\n    value: (yield) = 1\n",
    "try:\n    import a\nexcept ImportError:\n    import b\nelse:\n    import c\n",
    "def outer():\n    x = 1\n    def inner(y: x) -> x:\n        return x\n    return inner\n",
    "class A:\n    def m(self) -> 'A':\n        return [n for n in range(3) if super()]\n",
    "def __classdict__[__classdict__](): pass\n",
)


def dump_tree_str(text_str: str) -> str:
    """CPython's tree dump, as scripts/parser_parity.py prints it."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            tree = ast.parse(text_str)
        except (SyntaxError, ValueError) as error:
            return f"ERROR {getattr(error, 'lineno', 0)}"
    extra_dict = {"show_empty": True} if sys.version_info >= (3, 13) else {}
    return ast.dump(tree, include_attributes=True, **extra_dict)


def compile_outcome_str(text_str: str) -> str:
    """compile()'s outcome, as scripts/compile_parity.py prints it."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            compile(text_str, "case.py", "exec", dont_inherit=True)
        except SyntaxError as error:
            return f"ERROR {error.lineno} {error.offset} {error.msg}"
    return "OK"


def symtable_str(text_str: str) -> str:
    """The symbol table dump, as scripts/symtable_parity.py prints it."""
    if compile_outcome_str(text_str) != "OK":
        return "SKIP"
    entries_list = []

    def visit(table, depth_int):
        entries_list.append(f"{depth_int} {table.get_type()} "
                            f"{table.get_name()} {table.get_lineno()}")
        raw_symbols = table._table.symbols
        entries_list.extend(f"{depth_int} . {name} {raw_symbols[name]}"
                            for name in sorted(raw_symbols))
        for child in table.get_children():
            visit(child, depth_int + 1)

    visit(symtable.symtable(text_str, "case.py", "exec"), 0)
    return "; ".join(entries_list)


def rust_str(text_str: str) -> str:
    """A one-line Rust string literal for the text (escaped, so the test
    files are the same whatever line endings a checkout uses)."""
    parts_list = []
    for char_str in text_str:
        if char_str in '\\"':
            parts_list.append("\\" + char_str)
        elif char_str == "\n":
            parts_list.append("\\n")
        elif char_str == "\r":
            parts_list.append("\\r")
        elif char_str == "\t":
            parts_list.append("\\t")
        elif ord(char_str) < 0x20 or ord(char_str) == 0x7F:
            parts_list.append(f"\\u{{{ord(char_str):x}}}")
        else:
            parts_list.append(char_str)
    return '"' + "".join(parts_list) + '"'


def main() -> None:
    """Write cases_3X.rs for the running interpreter."""
    minor_int = sys.version_info.minor
    rows_list = []
    for source_str in SOURCES_TUPLE:
        rows_list.append(
            f"    ({rust_str(source_str)}, {rust_str(dump_tree_str(source_str))}, "
            f"{rust_str(compile_outcome_str(source_str))}, {rust_str(symtable_str(source_str))}),")
    folder = Path(sys.argv[1])
    folder.mkdir(parents=True, exist_ok=True)
    text_str = (
        f"// @generated by scripts/gen_version_cases.py with Python 3.{minor_int}.\n"
        "// (source, ast.dump, compile outcome, symbol table dump)\n"
        f"pub const CASES: &[(&str, &str, &str, &str)] = &[\n"
        + "\n".join(rows_list) + "\n];\n")
    (folder / f"cases_3{minor_int}.rs").write_text(text_str, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
