"""Record CPython 3.12 ast.dump results as Rust regression tests.

Usage: python3.12 scripts/gen_parser_cases.py rust/crates/parser/tests/recorded.rs

Each snippet's expected output is ast.dump(ast.parse(snippet),
include_attributes=True), or "ERROR line" for a syntax error, so the Rust
parser's tests compare against what CPython itself produced.
"""

import ast
from pathlib import Path
import sys
import warnings

SNIPPETS_TUPLE = (
    # f-strings: merged constants, specs, debug text, doubled braces
    'f"a{b!r:>{w}}c" "d"\n',
    'x = "a" f"{b=}" \'c\'\n',
    'f"{a:x}" f"{i:}" f"{1:{2}}"\n',
    'f"{a}{{b}}" rf"\\d{x}"\n',
    'f"{x!r}" f"""{\ny\n}"""\n',
    'f"{a:\\N{EN DASH}}" "\\N{ESC}" "\\N{BYTE ORDER MARK}"\n',
    # statements and positions
    '@d\ndef f[T: int, *U, **V](a, /, b=1, *c, d, e=2, **f) -> int: pass\n',
    'x: int = 1\n(y): int\nz.a: str\n',
    'with (a, b): pass\nwith (a, b) as c: pass\n',
    'if a:\n    b = 1;\nelif c:\n    pass\nelse:\n    d\n',
    'try:\n  pass\nexcept* E as e:\n  pass\nfinally:\n  x\n',
    'from ..a import (b as c, d,)\nimport x.y as z\nfrom . import *\n',
    'type X[T] = list[T]\nmatch = 1\nmatch(x)\n',
    'match x:\n    case [1, *r] | {"k": v, **kw} if v: pass\n'
    '    case C(a, b=c) as d: pass\n    case -1+2j | None | a.b: pass\n',
    # expressions
    'lambda x, *y, z=1, **k: 0\n',
    'a[1:2, ::3, *b]\nb[:]\nf(x for x in y)\n',
    'del a, (b, c)\nglobal a, b\nx = yield\n',
    'a if b else c\nnot a\n-1 ** 2\nawait x\n',
    'u"x" "y"\nb"\\x00" b\'\\777\'\n',
    '0xFFFF_FFFF_FFFF_FFFF_FF + 1e16 + 2001599834386887.25 + 1.5j\n',
    '{**a, b: c}\n{x for x in y if x}\n{k: v async for k, v in z}\n',
    # syntax errors (line only)
    'f(a=1,\n b,\n c\n)\nx = 1\n',
    'f(a=1,\n b c)\n',
    'x = (a if b\n)\n',
    '{a: 1, b\n}\n',
    'x = (1,\n',
    'x = (\n1]\n',
    'def f():\n  x = 1\n y = 2\n',
    'if x:\n',
    'x = 0123\n',
    'x = 1abc\n',
    'def f(*, **k): pass\n',
    'def f(a=1, b): pass\n',
    'x = 1 +\n"""abc\n',
)


def expected_str(source_str: str) -> str:
    """Return CPython's dump or error line for one snippet.

    Args:
        source_str (str): Python source.
    Returns:
        str: ast.dump with attributes, or "ERROR line".
    """
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            return ast.dump(ast.parse(source_str), include_attributes=True)
        except (SyntaxError, ValueError) as error:
            return f"ERROR {getattr(error, 'lineno', 0)}"


def rust_literal_str(text_str: str) -> str:
    """Return a Rust raw string literal holding the text.

    Args:
        text_str (str): Text to embed.
    Returns:
        str: r##"..."## literal.
    """
    return 'r##"' + text_str + '"##'


def main() -> int:
    """Write the recorded test file.

    Args:
        None: Reads sys.argv.
    Returns:
        int: 0 on success.
    """
    lines_list = [
        "//! Generated by scripts/gen_parser_cases.py from CPython "
        f"{sys.version.split()[0]}; do not edit.",
        "",
        "#[test]",
        "fn recorded_cpython_dumps() {",
        "    let cases: &[(&str, &str)] = &[",
    ]
    for source_str in SNIPPETS_TUPLE:
        lines_list.append(f"        ({rust_literal_str(source_str)}, "
                          f"{rust_literal_str(expected_str(source_str))}),")
    lines_list += [
        "    ];",
        "    for (source, expected) in cases {",
        "        assert_eq!(refactrail_parser::dump_source(source, true), *expected, \"source: {source:?}\");",
        "    }",
        "}",
        "",
    ]
    Path(sys.argv[1]).write_text("\n".join(lines_list), encoding="utf-8")
    print(f"{len(SNIPPETS_TUPLE)} cases recorded")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
