// @generated by scripts/gen_ast.py from CPython 3.12's ASDL; do not edit.
//! RefacTrail's typed Python syntax tree (CPython `ast` shape), its
//! exact `ast.dump` writer and a visitor walking children in field order.

#![allow(clippy::all)]

use crate::node::{write_constant, write_ident, Constant, Loc};

/// An identifier as CPython keeps it (inline when short).
pub type Id = crate::small_str::SmallStr;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ExprContext { Load, Store, Del }
impl ExprContext {
    pub fn name(self) -> &'static str {
        match self { ExprContext::Load => "Load", ExprContext::Store => "Store", ExprContext::Del => "Del", }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BoolOperator { And, Or }
impl BoolOperator {
    pub fn name(self) -> &'static str {
        match self { BoolOperator::And => "And", BoolOperator::Or => "Or", }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Operator { Add, Sub, Mult, MatMult, Div, Mod, Pow, LShift, RShift, BitOr, BitXor, BitAnd, FloorDiv }
impl Operator {
    pub fn name(self) -> &'static str {
        match self { Operator::Add => "Add", Operator::Sub => "Sub", Operator::Mult => "Mult", Operator::MatMult => "MatMult", Operator::Div => "Div", Operator::Mod => "Mod", Operator::Pow => "Pow", Operator::LShift => "LShift", Operator::RShift => "RShift", Operator::BitOr => "BitOr", Operator::BitXor => "BitXor", Operator::BitAnd => "BitAnd", Operator::FloorDiv => "FloorDiv", }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UnaryOperator { Invert, Not, UAdd, USub }
impl UnaryOperator {
    pub fn name(self) -> &'static str {
        match self { UnaryOperator::Invert => "Invert", UnaryOperator::Not => "Not", UnaryOperator::UAdd => "UAdd", UnaryOperator::USub => "USub", }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CmpOperator { Eq, NotEq, Lt, LtE, Gt, GtE, Is, IsNot, In, NotIn }
impl CmpOperator {
    pub fn name(self) -> &'static str {
        match self { CmpOperator::Eq => "Eq", CmpOperator::NotEq => "NotEq", CmpOperator::Lt => "Lt", CmpOperator::LtE => "LtE", CmpOperator::Gt => "Gt", CmpOperator::GtE => "GtE", CmpOperator::Is => "Is", CmpOperator::IsNot => "IsNot", CmpOperator::In => "In", CmpOperator::NotIn => "NotIn", }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Stmt { pub kind: StmtKind, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub enum StmtKind {
    FunctionDef { name: Id, args: Box<Arguments>, body: Vec<Stmt>, decorator_list: Vec<Expr>, returns: Option<Box<Expr>>, type_comment: Option<Box<str>>, type_params: Vec<TypeParam> },
    AsyncFunctionDef { name: Id, args: Box<Arguments>, body: Vec<Stmt>, decorator_list: Vec<Expr>, returns: Option<Box<Expr>>, type_comment: Option<Box<str>>, type_params: Vec<TypeParam> },
    ClassDef { name: Id, bases: Vec<Expr>, keywords: Vec<Keyword>, body: Vec<Stmt>, decorator_list: Vec<Expr>, type_params: Vec<TypeParam> },
    Return { value: Option<Box<Expr>> },
    Delete { targets: Vec<Expr> },
    Assign { targets: Vec<Expr>, value: Box<Expr>, type_comment: Option<Box<str>> },
    TypeAlias { name: Box<Expr>, type_params: Vec<TypeParam>, value: Box<Expr> },
    AugAssign { target: Box<Expr>, op: Operator, value: Box<Expr> },
    AnnAssign { target: Box<Expr>, annotation: Box<Expr>, value: Option<Box<Expr>>, simple: i64 },
    For { target: Box<Expr>, iter: Box<Expr>, body: Vec<Stmt>, orelse: Vec<Stmt>, type_comment: Option<Box<str>> },
    AsyncFor { target: Box<Expr>, iter: Box<Expr>, body: Vec<Stmt>, orelse: Vec<Stmt>, type_comment: Option<Box<str>> },
    While { test: Box<Expr>, body: Vec<Stmt>, orelse: Vec<Stmt> },
    If { test: Box<Expr>, body: Vec<Stmt>, orelse: Vec<Stmt> },
    With { items: Vec<WithItem>, body: Vec<Stmt>, type_comment: Option<Box<str>> },
    AsyncWith { items: Vec<WithItem>, body: Vec<Stmt>, type_comment: Option<Box<str>> },
    Match { subject: Box<Expr>, cases: Vec<MatchCase> },
    Raise { exc: Option<Box<Expr>>, cause: Option<Box<Expr>> },
    Try { body: Vec<Stmt>, handlers: Vec<ExceptHandler>, orelse: Vec<Stmt>, finalbody: Vec<Stmt> },
    TryStar { body: Vec<Stmt>, handlers: Vec<ExceptHandler>, orelse: Vec<Stmt>, finalbody: Vec<Stmt> },
    Assert { test: Box<Expr>, msg: Option<Box<Expr>> },
    Import { names: Vec<Alias> },
    ImportFrom { module: Option<Id>, names: Vec<Alias>, level: i64 },
    Global { names: Vec<Id> },
    Nonlocal { names: Vec<Id> },
    Expr { value: Box<Expr> },
    Pass,
    Break,
    Continue,
}
impl StmtKind {
    /// The CPython class name.
    pub fn name(&self) -> &'static str {
        match self { StmtKind::FunctionDef { .. } => "FunctionDef", StmtKind::AsyncFunctionDef { .. } => "AsyncFunctionDef", StmtKind::ClassDef { .. } => "ClassDef", StmtKind::Return { .. } => "Return", StmtKind::Delete { .. } => "Delete", StmtKind::Assign { .. } => "Assign", StmtKind::TypeAlias { .. } => "TypeAlias", StmtKind::AugAssign { .. } => "AugAssign", StmtKind::AnnAssign { .. } => "AnnAssign", StmtKind::For { .. } => "For", StmtKind::AsyncFor { .. } => "AsyncFor", StmtKind::While { .. } => "While", StmtKind::If { .. } => "If", StmtKind::With { .. } => "With", StmtKind::AsyncWith { .. } => "AsyncWith", StmtKind::Match { .. } => "Match", StmtKind::Raise { .. } => "Raise", StmtKind::Try { .. } => "Try", StmtKind::TryStar { .. } => "TryStar", StmtKind::Assert { .. } => "Assert", StmtKind::Import { .. } => "Import", StmtKind::ImportFrom { .. } => "ImportFrom", StmtKind::Global { .. } => "Global", StmtKind::Nonlocal { .. } => "Nonlocal", StmtKind::Expr { .. } => "Expr", StmtKind::Pass => "Pass", StmtKind::Break => "Break", StmtKind::Continue => "Continue", }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Expr { pub kind: ExprKind, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub enum ExprKind {
    BoolOp { op: BoolOperator, values: Vec<Expr> },
    NamedExpr { target: Box<Expr>, value: Box<Expr> },
    BinOp { left: Box<Expr>, op: Operator, right: Box<Expr> },
    UnaryOp { op: UnaryOperator, operand: Box<Expr> },
    Lambda { args: Box<Arguments>, body: Box<Expr> },
    IfExp { test: Box<Expr>, body: Box<Expr>, orelse: Box<Expr> },
    Dict { keys: Vec<Option<Expr>>, values: Vec<Expr> },
    Set { elts: Vec<Expr> },
    ListComp { elt: Box<Expr>, generators: Vec<Comprehension> },
    SetComp { elt: Box<Expr>, generators: Vec<Comprehension> },
    DictComp { key: Box<Expr>, value: Box<Expr>, generators: Vec<Comprehension> },
    GeneratorExp { elt: Box<Expr>, generators: Vec<Comprehension> },
    Await { value: Box<Expr> },
    Yield { value: Option<Box<Expr>> },
    YieldFrom { value: Box<Expr> },
    Compare { left: Box<Expr>, ops: Vec<CmpOperator>, comparators: Vec<Expr> },
    Call { func: Box<Expr>, args: Vec<Expr>, keywords: Vec<Keyword> },
    FormattedValue { value: Box<Expr>, conversion: i64, format_spec: Option<Box<Expr>> },
    JoinedStr { values: Vec<Expr> },
    Constant { value: Constant, kind: Option<Box<str>> },
    Attribute { value: Box<Expr>, attr: Id, ctx: ExprContext },
    Subscript { value: Box<Expr>, slice: Box<Expr>, ctx: ExprContext },
    Starred { value: Box<Expr>, ctx: ExprContext },
    Name { id: Id, ctx: ExprContext },
    List { elts: Vec<Expr>, ctx: ExprContext },
    Tuple { elts: Vec<Expr>, ctx: ExprContext },
    Slice { lower: Option<Box<Expr>>, upper: Option<Box<Expr>>, step: Option<Box<Expr>> },
}
impl ExprKind {
    /// The CPython class name.
    pub fn name(&self) -> &'static str {
        match self { ExprKind::BoolOp { .. } => "BoolOp", ExprKind::NamedExpr { .. } => "NamedExpr", ExprKind::BinOp { .. } => "BinOp", ExprKind::UnaryOp { .. } => "UnaryOp", ExprKind::Lambda { .. } => "Lambda", ExprKind::IfExp { .. } => "IfExp", ExprKind::Dict { .. } => "Dict", ExprKind::Set { .. } => "Set", ExprKind::ListComp { .. } => "ListComp", ExprKind::SetComp { .. } => "SetComp", ExprKind::DictComp { .. } => "DictComp", ExprKind::GeneratorExp { .. } => "GeneratorExp", ExprKind::Await { .. } => "Await", ExprKind::Yield { .. } => "Yield", ExprKind::YieldFrom { .. } => "YieldFrom", ExprKind::Compare { .. } => "Compare", ExprKind::Call { .. } => "Call", ExprKind::FormattedValue { .. } => "FormattedValue", ExprKind::JoinedStr { .. } => "JoinedStr", ExprKind::Constant { .. } => "Constant", ExprKind::Attribute { .. } => "Attribute", ExprKind::Subscript { .. } => "Subscript", ExprKind::Starred { .. } => "Starred", ExprKind::Name { .. } => "Name", ExprKind::List { .. } => "List", ExprKind::Tuple { .. } => "Tuple", ExprKind::Slice { .. } => "Slice", }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Pattern { pub kind: PatternKind, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub enum PatternKind {
    MatchValue { value: Box<Expr> },
    MatchSingleton { value: Constant },
    MatchSequence { patterns: Vec<Pattern> },
    MatchMapping { keys: Vec<Expr>, patterns: Vec<Pattern>, rest: Option<Id> },
    MatchClass { cls: Box<Expr>, patterns: Vec<Pattern>, kwd_attrs: Vec<Id>, kwd_patterns: Vec<Pattern> },
    MatchStar { name: Option<Id> },
    MatchAs { pattern: Option<Box<Pattern>>, name: Option<Id> },
    MatchOr { patterns: Vec<Pattern> },
}
impl PatternKind {
    /// The CPython class name.
    pub fn name(&self) -> &'static str {
        match self { PatternKind::MatchValue { .. } => "MatchValue", PatternKind::MatchSingleton { .. } => "MatchSingleton", PatternKind::MatchSequence { .. } => "MatchSequence", PatternKind::MatchMapping { .. } => "MatchMapping", PatternKind::MatchClass { .. } => "MatchClass", PatternKind::MatchStar { .. } => "MatchStar", PatternKind::MatchAs { .. } => "MatchAs", PatternKind::MatchOr { .. } => "MatchOr", }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeParam { pub kind: TypeParamKind, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub enum TypeParamKind {
    TypeVar { name: Id, bound: Option<Box<Expr>> },
    ParamSpec { name: Id },
    TypeVarTuple { name: Id },
}
impl TypeParamKind {
    /// The CPython class name.
    pub fn name(&self) -> &'static str {
        match self { TypeParamKind::TypeVar { .. } => "TypeVar", TypeParamKind::ParamSpec { .. } => "ParamSpec", TypeParamKind::TypeVarTuple { .. } => "TypeVarTuple", }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct ExceptHandler { pub type_: Option<Box<Expr>>, pub name: Option<Id>, pub body: Vec<Stmt>, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub struct Arguments { pub posonlyargs: Vec<Arg>, pub args: Vec<Arg>, pub vararg: Option<Arg>, pub kwonlyargs: Vec<Arg>, pub kw_defaults: Vec<Option<Expr>>, pub kwarg: Option<Arg>, pub defaults: Vec<Expr> }

#[derive(Clone, Debug, PartialEq)]
pub struct Arg { pub arg: Id, pub annotation: Option<Box<Expr>>, pub type_comment: Option<Box<str>>, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub struct Keyword { pub arg: Option<Id>, pub value: Box<Expr>, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub struct Alias { pub name: Id, pub asname: Option<Id>, pub loc: Loc }

#[derive(Clone, Debug, PartialEq)]
pub struct WithItem { pub context_expr: Box<Expr>, pub optional_vars: Option<Box<Expr>> }

#[derive(Clone, Debug, PartialEq)]
pub struct MatchCase { pub pattern: Box<Pattern>, pub guard: Option<Box<Expr>>, pub body: Vec<Stmt> }

#[derive(Clone, Debug, PartialEq)]
pub struct Comprehension { pub target: Box<Expr>, pub iter: Box<Expr>, pub ifs: Vec<Expr>, pub is_async: i64 }

#[derive(Clone, Debug, PartialEq)]
pub struct Module { pub body: Vec<Stmt> }

fn sep(out: &mut String, first: &mut bool) {
    if !*first {
        out.push_str(", ");
    }
    *first = false;
}

fn write_loc(out: &mut String, first: &mut bool, loc: &Loc) {
    for (name, number) in [("lineno", loc.line), ("col_offset", loc.col), ("end_lineno", loc.end_line), ("end_col_offset", loc.end_col)] {
        sep(out, first);
        out.push_str(name);
        out.push('=');
        out.push_str(&number.to_string());
    }
}

/// `ast.dump(module, include_attributes=attributes)`.
pub fn dump_module(module: &Module, attributes: bool) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("Module(body=[");
    for (index, item) in module.body.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        write_stmt(&mut out, item, attributes);
    }
    out.push_str("], type_ignores=[])");
    out
}

pub fn write_stmt(out: &mut String, node: &Stmt, attributes: bool) {
    let mut first = true;
    match &node.kind {
        StmtKind::FunctionDef { name, args, body, decorator_list, returns, type_comment, type_params } => {
        out.push_str("FunctionDef(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        sep(out, &mut first); out.push_str("args="); write_arguments(out, args, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("decorator_list="); out.push('['); for (index, item) in (decorator_list).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        if let Some(value) = returns { sep(out, &mut first); out.push_str("returns="); write_expr(out, value, attributes); }
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        sep(out, &mut first); out.push_str("type_params="); out.push('['); for (index, item) in (type_params).iter().enumerate() { if index > 0 { out.push_str(", "); } write_type_param(out, item, attributes); } out.push(']');
        }
        StmtKind::AsyncFunctionDef { name, args, body, decorator_list, returns, type_comment, type_params } => {
        out.push_str("AsyncFunctionDef(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        sep(out, &mut first); out.push_str("args="); write_arguments(out, args, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("decorator_list="); out.push('['); for (index, item) in (decorator_list).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        if let Some(value) = returns { sep(out, &mut first); out.push_str("returns="); write_expr(out, value, attributes); }
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        sep(out, &mut first); out.push_str("type_params="); out.push('['); for (index, item) in (type_params).iter().enumerate() { if index > 0 { out.push_str(", "); } write_type_param(out, item, attributes); } out.push(']');
        }
        StmtKind::ClassDef { name, bases, keywords, body, decorator_list, type_params } => {
        out.push_str("ClassDef(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        sep(out, &mut first); out.push_str("bases="); out.push('['); for (index, item) in (bases).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("keywords="); out.push('['); for (index, item) in (keywords).iter().enumerate() { if index > 0 { out.push_str(", "); } write_keyword(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("decorator_list="); out.push('['); for (index, item) in (decorator_list).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("type_params="); out.push('['); for (index, item) in (type_params).iter().enumerate() { if index > 0 { out.push_str(", "); } write_type_param(out, item, attributes); } out.push(']');
        }
        StmtKind::Return { value } => {
        out.push_str("Return(");
        if let Some(value) = value { sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes); }
        }
        StmtKind::Delete { targets } => {
        out.push_str("Delete(");
        sep(out, &mut first); out.push_str("targets="); out.push('['); for (index, item) in (targets).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        StmtKind::Assign { targets, value, type_comment } => {
        out.push_str("Assign(");
        sep(out, &mut first); out.push_str("targets="); out.push('['); for (index, item) in (targets).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        }
        StmtKind::TypeAlias { name, type_params, value } => {
        out.push_str("TypeAlias(");
        sep(out, &mut first); out.push_str("name="); write_expr(out, name, attributes);
        sep(out, &mut first); out.push_str("type_params="); out.push('['); for (index, item) in (type_params).iter().enumerate() { if index > 0 { out.push_str(", "); } write_type_param(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        StmtKind::AugAssign { target, op, value } => {
        out.push_str("AugAssign(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, target, attributes);
        sep(out, &mut first); out.push_str("op="); { out.push_str(op.name()); out.push_str("()") };
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        StmtKind::AnnAssign { target, annotation, value, simple } => {
        out.push_str("AnnAssign(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, target, attributes);
        sep(out, &mut first); out.push_str("annotation="); write_expr(out, annotation, attributes);
        if let Some(value) = value { sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes); }
        sep(out, &mut first); out.push_str("simple="); out.push_str(&(simple).to_string());
        }
        StmtKind::For { target, iter, body, orelse, type_comment } => {
        out.push_str("For(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, target, attributes);
        sep(out, &mut first); out.push_str("iter="); write_expr(out, iter, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        }
        StmtKind::AsyncFor { target, iter, body, orelse, type_comment } => {
        out.push_str("AsyncFor(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, target, attributes);
        sep(out, &mut first); out.push_str("iter="); write_expr(out, iter, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        }
        StmtKind::While { test, body, orelse } => {
        out.push_str("While(");
        sep(out, &mut first); out.push_str("test="); write_expr(out, test, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        }
        StmtKind::If { test, body, orelse } => {
        out.push_str("If(");
        sep(out, &mut first); out.push_str("test="); write_expr(out, test, attributes);
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        }
        StmtKind::With { items, body, type_comment } => {
        out.push_str("With(");
        sep(out, &mut first); out.push_str("items="); out.push('['); for (index, item) in (items).iter().enumerate() { if index > 0 { out.push_str(", "); } write_withitem(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        }
        StmtKind::AsyncWith { items, body, type_comment } => {
        out.push_str("AsyncWith(");
        sep(out, &mut first); out.push_str("items="); out.push('['); for (index, item) in (items).iter().enumerate() { if index > 0 { out.push_str(", "); } write_withitem(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        if let Some(value) = type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
        }
        StmtKind::Match { subject, cases } => {
        out.push_str("Match(");
        sep(out, &mut first); out.push_str("subject="); write_expr(out, subject, attributes);
        sep(out, &mut first); out.push_str("cases="); out.push('['); for (index, item) in (cases).iter().enumerate() { if index > 0 { out.push_str(", "); } write_match_case(out, item, attributes); } out.push(']');
        }
        StmtKind::Raise { exc, cause } => {
        out.push_str("Raise(");
        if let Some(value) = exc { sep(out, &mut first); out.push_str("exc="); write_expr(out, value, attributes); }
        if let Some(value) = cause { sep(out, &mut first); out.push_str("cause="); write_expr(out, value, attributes); }
        }
        StmtKind::Try { body, handlers, orelse, finalbody } => {
        out.push_str("Try(");
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("handlers="); out.push('['); for (index, item) in (handlers).iter().enumerate() { if index > 0 { out.push_str(", "); } write_excepthandler(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("finalbody="); out.push('['); for (index, item) in (finalbody).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        }
        StmtKind::TryStar { body, handlers, orelse, finalbody } => {
        out.push_str("TryStar(");
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("handlers="); out.push('['); for (index, item) in (handlers).iter().enumerate() { if index > 0 { out.push_str(", "); } write_excepthandler(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("orelse="); out.push('['); for (index, item) in (orelse).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("finalbody="); out.push('['); for (index, item) in (finalbody).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
        }
        StmtKind::Assert { test, msg } => {
        out.push_str("Assert(");
        sep(out, &mut first); out.push_str("test="); write_expr(out, test, attributes);
        if let Some(value) = msg { sep(out, &mut first); out.push_str("msg="); write_expr(out, value, attributes); }
        }
        StmtKind::Import { names } => {
        out.push_str("Import(");
        sep(out, &mut first); out.push_str("names="); out.push('['); for (index, item) in (names).iter().enumerate() { if index > 0 { out.push_str(", "); } write_alias(out, item, attributes); } out.push(']');
        }
        StmtKind::ImportFrom { module, names, level } => {
        out.push_str("ImportFrom(");
        if let Some(value) = module { sep(out, &mut first); out.push_str("module="); write_ident(out, value); }
        sep(out, &mut first); out.push_str("names="); out.push('['); for (index, item) in (names).iter().enumerate() { if index > 0 { out.push_str(", "); } write_alias(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("level="); out.push_str(&(level).to_string());
        }
        StmtKind::Global { names } => {
        out.push_str("Global(");
        sep(out, &mut first); out.push_str("names="); out.push('['); for (index, item) in (names).iter().enumerate() { if index > 0 { out.push_str(", "); } write_ident(out, item); } out.push(']');
        }
        StmtKind::Nonlocal { names } => {
        out.push_str("Nonlocal(");
        sep(out, &mut first); out.push_str("names="); out.push('['); for (index, item) in (names).iter().enumerate() { if index > 0 { out.push_str(", "); } write_ident(out, item); } out.push(']');
        }
        StmtKind::Expr { value } => {
        out.push_str("Expr(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        StmtKind::Pass => {
        out.push_str("Pass(");

        }
        StmtKind::Break => {
        out.push_str("Break(");

        }
        StmtKind::Continue => {
        out.push_str("Continue(");

        }
    }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_expr(out: &mut String, node: &Expr, attributes: bool) {
    let mut first = true;
    match &node.kind {
        ExprKind::BoolOp { op, values } => {
        out.push_str("BoolOp(");
        sep(out, &mut first); out.push_str("op="); { out.push_str(op.name()); out.push_str("()") };
        sep(out, &mut first); out.push_str("values="); out.push('['); for (index, item) in (values).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        ExprKind::NamedExpr { target, value } => {
        out.push_str("NamedExpr(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, target, attributes);
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        ExprKind::BinOp { left, op, right } => {
        out.push_str("BinOp(");
        sep(out, &mut first); out.push_str("left="); write_expr(out, left, attributes);
        sep(out, &mut first); out.push_str("op="); { out.push_str(op.name()); out.push_str("()") };
        sep(out, &mut first); out.push_str("right="); write_expr(out, right, attributes);
        }
        ExprKind::UnaryOp { op, operand } => {
        out.push_str("UnaryOp(");
        sep(out, &mut first); out.push_str("op="); { out.push_str(op.name()); out.push_str("()") };
        sep(out, &mut first); out.push_str("operand="); write_expr(out, operand, attributes);
        }
        ExprKind::Lambda { args, body } => {
        out.push_str("Lambda(");
        sep(out, &mut first); out.push_str("args="); write_arguments(out, args, attributes);
        sep(out, &mut first); out.push_str("body="); write_expr(out, body, attributes);
        }
        ExprKind::IfExp { test, body, orelse } => {
        out.push_str("IfExp(");
        sep(out, &mut first); out.push_str("test="); write_expr(out, test, attributes);
        sep(out, &mut first); out.push_str("body="); write_expr(out, body, attributes);
        sep(out, &mut first); out.push_str("orelse="); write_expr(out, orelse, attributes);
        }
        ExprKind::Dict { keys, values } => {
        out.push_str("Dict(");
        sep(out, &mut first); out.push_str("keys="); out.push('['); for (index, item) in (keys).iter().enumerate() { if index > 0 { out.push_str(", "); } match item { Some(value) => write_expr(out, value, attributes), None => out.push_str("None") } } out.push(']');
        sep(out, &mut first); out.push_str("values="); out.push('['); for (index, item) in (values).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        ExprKind::Set { elts } => {
        out.push_str("Set(");
        sep(out, &mut first); out.push_str("elts="); out.push('['); for (index, item) in (elts).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        ExprKind::ListComp { elt, generators } => {
        out.push_str("ListComp(");
        sep(out, &mut first); out.push_str("elt="); write_expr(out, elt, attributes);
        sep(out, &mut first); out.push_str("generators="); out.push('['); for (index, item) in (generators).iter().enumerate() { if index > 0 { out.push_str(", "); } write_comprehension(out, item, attributes); } out.push(']');
        }
        ExprKind::SetComp { elt, generators } => {
        out.push_str("SetComp(");
        sep(out, &mut first); out.push_str("elt="); write_expr(out, elt, attributes);
        sep(out, &mut first); out.push_str("generators="); out.push('['); for (index, item) in (generators).iter().enumerate() { if index > 0 { out.push_str(", "); } write_comprehension(out, item, attributes); } out.push(']');
        }
        ExprKind::DictComp { key, value, generators } => {
        out.push_str("DictComp(");
        sep(out, &mut first); out.push_str("key="); write_expr(out, key, attributes);
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        sep(out, &mut first); out.push_str("generators="); out.push('['); for (index, item) in (generators).iter().enumerate() { if index > 0 { out.push_str(", "); } write_comprehension(out, item, attributes); } out.push(']');
        }
        ExprKind::GeneratorExp { elt, generators } => {
        out.push_str("GeneratorExp(");
        sep(out, &mut first); out.push_str("elt="); write_expr(out, elt, attributes);
        sep(out, &mut first); out.push_str("generators="); out.push('['); for (index, item) in (generators).iter().enumerate() { if index > 0 { out.push_str(", "); } write_comprehension(out, item, attributes); } out.push(']');
        }
        ExprKind::Await { value } => {
        out.push_str("Await(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        ExprKind::Yield { value } => {
        out.push_str("Yield(");
        if let Some(value) = value { sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes); }
        }
        ExprKind::YieldFrom { value } => {
        out.push_str("YieldFrom(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        ExprKind::Compare { left, ops, comparators } => {
        out.push_str("Compare(");
        sep(out, &mut first); out.push_str("left="); write_expr(out, left, attributes);
        sep(out, &mut first); out.push_str("ops="); out.push('['); for (index, item) in (ops).iter().enumerate() { if index > 0 { out.push_str(", "); } { out.push_str(item.name()); out.push_str("()") }; } out.push(']');
        sep(out, &mut first); out.push_str("comparators="); out.push('['); for (index, item) in (comparators).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        ExprKind::Call { func, args, keywords } => {
        out.push_str("Call(");
        sep(out, &mut first); out.push_str("func="); write_expr(out, func, attributes);
        sep(out, &mut first); out.push_str("args="); out.push('['); for (index, item) in (args).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("keywords="); out.push('['); for (index, item) in (keywords).iter().enumerate() { if index > 0 { out.push_str(", "); } write_keyword(out, item, attributes); } out.push(']');
        }
        ExprKind::FormattedValue { value, conversion, format_spec } => {
        out.push_str("FormattedValue(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        sep(out, &mut first); out.push_str("conversion="); out.push_str(&(conversion).to_string());
        if let Some(value) = format_spec { sep(out, &mut first); out.push_str("format_spec="); write_expr(out, value, attributes); }
        }
        ExprKind::JoinedStr { values } => {
        out.push_str("JoinedStr(");
        sep(out, &mut first); out.push_str("values="); out.push('['); for (index, item) in (values).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        }
        ExprKind::Constant { value, kind } => {
        out.push_str("Constant(");
        sep(out, &mut first); out.push_str("value="); write_constant(out, value);
        if let Some(value) = kind { sep(out, &mut first); out.push_str("kind="); write_ident(out, value); }
        }
        ExprKind::Attribute { value, attr, ctx } => {
        out.push_str("Attribute(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        sep(out, &mut first); out.push_str("attr="); write_ident(out, attr);
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::Subscript { value, slice, ctx } => {
        out.push_str("Subscript(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        sep(out, &mut first); out.push_str("slice="); write_expr(out, slice, attributes);
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::Starred { value, ctx } => {
        out.push_str("Starred(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::Name { id, ctx } => {
        out.push_str("Name(");
        sep(out, &mut first); out.push_str("id="); write_ident(out, id);
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::List { elts, ctx } => {
        out.push_str("List(");
        sep(out, &mut first); out.push_str("elts="); out.push('['); for (index, item) in (elts).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::Tuple { elts, ctx } => {
        out.push_str("Tuple(");
        sep(out, &mut first); out.push_str("elts="); out.push('['); for (index, item) in (elts).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("ctx="); { out.push_str(ctx.name()); out.push_str("()") };
        }
        ExprKind::Slice { lower, upper, step } => {
        out.push_str("Slice(");
        if let Some(value) = lower { sep(out, &mut first); out.push_str("lower="); write_expr(out, value, attributes); }
        if let Some(value) = upper { sep(out, &mut first); out.push_str("upper="); write_expr(out, value, attributes); }
        if let Some(value) = step { sep(out, &mut first); out.push_str("step="); write_expr(out, value, attributes); }
        }
    }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_pattern(out: &mut String, node: &Pattern, attributes: bool) {
    let mut first = true;
    match &node.kind {
        PatternKind::MatchValue { value } => {
        out.push_str("MatchValue(");
        sep(out, &mut first); out.push_str("value="); write_expr(out, value, attributes);
        }
        PatternKind::MatchSingleton { value } => {
        out.push_str("MatchSingleton(");
        sep(out, &mut first); out.push_str("value="); write_constant(out, value);
        }
        PatternKind::MatchSequence { patterns } => {
        out.push_str("MatchSequence(");
        sep(out, &mut first); out.push_str("patterns="); out.push('['); for (index, item) in (patterns).iter().enumerate() { if index > 0 { out.push_str(", "); } write_pattern(out, item, attributes); } out.push(']');
        }
        PatternKind::MatchMapping { keys, patterns, rest } => {
        out.push_str("MatchMapping(");
        sep(out, &mut first); out.push_str("keys="); out.push('['); for (index, item) in (keys).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("patterns="); out.push('['); for (index, item) in (patterns).iter().enumerate() { if index > 0 { out.push_str(", "); } write_pattern(out, item, attributes); } out.push(']');
        if let Some(value) = rest { sep(out, &mut first); out.push_str("rest="); write_ident(out, value); }
        }
        PatternKind::MatchClass { cls, patterns, kwd_attrs, kwd_patterns } => {
        out.push_str("MatchClass(");
        sep(out, &mut first); out.push_str("cls="); write_expr(out, cls, attributes);
        sep(out, &mut first); out.push_str("patterns="); out.push('['); for (index, item) in (patterns).iter().enumerate() { if index > 0 { out.push_str(", "); } write_pattern(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("kwd_attrs="); out.push('['); for (index, item) in (kwd_attrs).iter().enumerate() { if index > 0 { out.push_str(", "); } write_ident(out, item); } out.push(']');
        sep(out, &mut first); out.push_str("kwd_patterns="); out.push('['); for (index, item) in (kwd_patterns).iter().enumerate() { if index > 0 { out.push_str(", "); } write_pattern(out, item, attributes); } out.push(']');
        }
        PatternKind::MatchStar { name } => {
        out.push_str("MatchStar(");
        if let Some(value) = name { sep(out, &mut first); out.push_str("name="); write_ident(out, value); }
        }
        PatternKind::MatchAs { pattern, name } => {
        out.push_str("MatchAs(");
        if let Some(value) = pattern { sep(out, &mut first); out.push_str("pattern="); write_pattern(out, value, attributes); }
        if let Some(value) = name { sep(out, &mut first); out.push_str("name="); write_ident(out, value); }
        }
        PatternKind::MatchOr { patterns } => {
        out.push_str("MatchOr(");
        sep(out, &mut first); out.push_str("patterns="); out.push('['); for (index, item) in (patterns).iter().enumerate() { if index > 0 { out.push_str(", "); } write_pattern(out, item, attributes); } out.push(']');
        }
    }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_type_param(out: &mut String, node: &TypeParam, attributes: bool) {
    let mut first = true;
    match &node.kind {
        TypeParamKind::TypeVar { name, bound } => {
        out.push_str("TypeVar(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        if let Some(value) = bound { sep(out, &mut first); out.push_str("bound="); write_expr(out, value, attributes); }
        }
        TypeParamKind::ParamSpec { name } => {
        out.push_str("ParamSpec(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        }
        TypeParamKind::TypeVarTuple { name } => {
        out.push_str("TypeVarTuple(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, name);
        }
    }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_excepthandler(out: &mut String, node: &ExceptHandler, attributes: bool) {
    let mut first = true;
    out.push_str("ExceptHandler(");
        if let Some(value) = &node.type_ { sep(out, &mut first); out.push_str("type="); write_expr(out, value, attributes); }
        if let Some(value) = &node.name { sep(out, &mut first); out.push_str("name="); write_ident(out, value); }
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (&node.body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_arguments(out: &mut String, node: &Arguments, attributes: bool) {
    let mut first = true;
    out.push_str("arguments(");
        sep(out, &mut first); out.push_str("posonlyargs="); out.push('['); for (index, item) in (&node.posonlyargs).iter().enumerate() { if index > 0 { out.push_str(", "); } write_arg(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("args="); out.push('['); for (index, item) in (&node.args).iter().enumerate() { if index > 0 { out.push_str(", "); } write_arg(out, item, attributes); } out.push(']');
        if let Some(value) = &node.vararg { sep(out, &mut first); out.push_str("vararg="); write_arg(out, value, attributes); }
        sep(out, &mut first); out.push_str("kwonlyargs="); out.push('['); for (index, item) in (&node.kwonlyargs).iter().enumerate() { if index > 0 { out.push_str(", "); } write_arg(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("kw_defaults="); out.push('['); for (index, item) in (&node.kw_defaults).iter().enumerate() { if index > 0 { out.push_str(", "); } match item { Some(value) => write_expr(out, value, attributes), None => out.push_str("None") } } out.push(']');
        if let Some(value) = &node.kwarg { sep(out, &mut first); out.push_str("kwarg="); write_arg(out, value, attributes); }
        sep(out, &mut first); out.push_str("defaults="); out.push('['); for (index, item) in (&node.defaults).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
    let _ = attributes;
    out.push(')');
}

pub fn write_arg(out: &mut String, node: &Arg, attributes: bool) {
    let mut first = true;
    out.push_str("arg(");
        sep(out, &mut first); out.push_str("arg="); write_ident(out, &node.arg);
        if let Some(value) = &node.annotation { sep(out, &mut first); out.push_str("annotation="); write_expr(out, value, attributes); }
        if let Some(value) = &node.type_comment { sep(out, &mut first); out.push_str("type_comment="); write_ident(out, value); }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_keyword(out: &mut String, node: &Keyword, attributes: bool) {
    let mut first = true;
    out.push_str("keyword(");
        if let Some(value) = &node.arg { sep(out, &mut first); out.push_str("arg="); write_ident(out, value); }
        sep(out, &mut first); out.push_str("value="); write_expr(out, &node.value, attributes);
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_alias(out: &mut String, node: &Alias, attributes: bool) {
    let mut first = true;
    out.push_str("alias(");
        sep(out, &mut first); out.push_str("name="); write_ident(out, &node.name);
        if let Some(value) = &node.asname { sep(out, &mut first); out.push_str("asname="); write_ident(out, value); }
    if attributes { write_loc(out, &mut first, &node.loc); }
    out.push(')');
}

pub fn write_withitem(out: &mut String, node: &WithItem, attributes: bool) {
    let mut first = true;
    out.push_str("withitem(");
        sep(out, &mut first); out.push_str("context_expr="); write_expr(out, &node.context_expr, attributes);
        if let Some(value) = &node.optional_vars { sep(out, &mut first); out.push_str("optional_vars="); write_expr(out, value, attributes); }
    let _ = attributes;
    out.push(')');
}

pub fn write_match_case(out: &mut String, node: &MatchCase, attributes: bool) {
    let mut first = true;
    out.push_str("match_case(");
        sep(out, &mut first); out.push_str("pattern="); write_pattern(out, &node.pattern, attributes);
        if let Some(value) = &node.guard { sep(out, &mut first); out.push_str("guard="); write_expr(out, value, attributes); }
        sep(out, &mut first); out.push_str("body="); out.push('['); for (index, item) in (&node.body).iter().enumerate() { if index > 0 { out.push_str(", "); } write_stmt(out, item, attributes); } out.push(']');
    let _ = attributes;
    out.push(')');
}

pub fn write_comprehension(out: &mut String, node: &Comprehension, attributes: bool) {
    let mut first = true;
    out.push_str("comprehension(");
        sep(out, &mut first); out.push_str("target="); write_expr(out, &node.target, attributes);
        sep(out, &mut first); out.push_str("iter="); write_expr(out, &node.iter, attributes);
        sep(out, &mut first); out.push_str("ifs="); out.push('['); for (index, item) in (&node.ifs).iter().enumerate() { if index > 0 { out.push_str(", "); } write_expr(out, item, attributes); } out.push(']');
        sep(out, &mut first); out.push_str("is_async="); out.push_str(&(&node.is_async).to_string());
    let _ = attributes;
    out.push(')');
}

/// A tree visitor; each default visits the node's children in field
/// order (CPython's `ast.iter_child_nodes`).
pub trait Visitor<'a>: Sized {
    fn visit_stmt(&mut self, node: &'a Stmt) { walk_stmt(self, node) }
    fn visit_expr(&mut self, node: &'a Expr) { walk_expr(self, node) }
    fn visit_pattern(&mut self, node: &'a Pattern) { walk_pattern(self, node) }
    fn visit_type_param(&mut self, node: &'a TypeParam) { walk_type_param(self, node) }
    fn visit_excepthandler(&mut self, node: &'a ExceptHandler) { walk_excepthandler(self, node) }
    fn visit_arguments(&mut self, node: &'a Arguments) { walk_arguments(self, node) }
    fn visit_arg(&mut self, node: &'a Arg) { walk_arg(self, node) }
    fn visit_keyword(&mut self, node: &'a Keyword) { walk_keyword(self, node) }
    fn visit_alias(&mut self, node: &'a Alias) { walk_alias(self, node) }
    fn visit_withitem(&mut self, node: &'a WithItem) { walk_withitem(self, node) }
    fn visit_match_case(&mut self, node: &'a MatchCase) { walk_match_case(self, node) }
    fn visit_comprehension(&mut self, node: &'a Comprehension) { walk_comprehension(self, node) }
}

pub fn walk_stmt<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Stmt) {
    match &node.kind {
        StmtKind::FunctionDef { args, body, decorator_list, returns, type_params, .. } => {
        visitor.visit_arguments(args);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in decorator_list.iter() { visitor.visit_expr(item); }
        if let Some(item) = returns { visitor.visit_expr(item); }
        for item in type_params.iter() { visitor.visit_type_param(item); }
        }
        StmtKind::AsyncFunctionDef { args, body, decorator_list, returns, type_params, .. } => {
        visitor.visit_arguments(args);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in decorator_list.iter() { visitor.visit_expr(item); }
        if let Some(item) = returns { visitor.visit_expr(item); }
        for item in type_params.iter() { visitor.visit_type_param(item); }
        }
        StmtKind::ClassDef { bases, keywords, body, decorator_list, type_params, .. } => {
        for item in bases.iter() { visitor.visit_expr(item); }
        for item in keywords.iter() { visitor.visit_keyword(item); }
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in decorator_list.iter() { visitor.visit_expr(item); }
        for item in type_params.iter() { visitor.visit_type_param(item); }
        }
        StmtKind::Return { value } => {
        if let Some(item) = value { visitor.visit_expr(item); }
        }
        StmtKind::Delete { targets } => {
        for item in targets.iter() { visitor.visit_expr(item); }
        }
        StmtKind::Assign { targets, value, .. } => {
        for item in targets.iter() { visitor.visit_expr(item); }
        visitor.visit_expr(value);
        }
        StmtKind::TypeAlias { name, type_params, value } => {
        visitor.visit_expr(name);
        for item in type_params.iter() { visitor.visit_type_param(item); }
        visitor.visit_expr(value);
        }
        StmtKind::AugAssign { target, value, .. } => {
        visitor.visit_expr(target);
        visitor.visit_expr(value);
        }
        StmtKind::AnnAssign { target, annotation, value, .. } => {
        visitor.visit_expr(target);
        visitor.visit_expr(annotation);
        if let Some(item) = value { visitor.visit_expr(item); }
        }
        StmtKind::For { target, iter, body, orelse, .. } => {
        visitor.visit_expr(target);
        visitor.visit_expr(iter);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::AsyncFor { target, iter, body, orelse, .. } => {
        visitor.visit_expr(target);
        visitor.visit_expr(iter);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::While { test, body, orelse } => {
        visitor.visit_expr(test);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::If { test, body, orelse } => {
        visitor.visit_expr(test);
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::With { items, body, .. } => {
        for item in items.iter() { visitor.visit_withitem(item); }
        for item in body.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::AsyncWith { items, body, .. } => {
        for item in items.iter() { visitor.visit_withitem(item); }
        for item in body.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::Match { subject, cases } => {
        visitor.visit_expr(subject);
        for item in cases.iter() { visitor.visit_match_case(item); }
        }
        StmtKind::Raise { exc, cause } => {
        if let Some(item) = exc { visitor.visit_expr(item); }
        if let Some(item) = cause { visitor.visit_expr(item); }
        }
        StmtKind::Try { body, handlers, orelse, finalbody } => {
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in handlers.iter() { visitor.visit_excepthandler(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        for item in finalbody.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::TryStar { body, handlers, orelse, finalbody } => {
        for item in body.iter() { visitor.visit_stmt(item); }
        for item in handlers.iter() { visitor.visit_excepthandler(item); }
        for item in orelse.iter() { visitor.visit_stmt(item); }
        for item in finalbody.iter() { visitor.visit_stmt(item); }
        }
        StmtKind::Assert { test, msg } => {
        visitor.visit_expr(test);
        if let Some(item) = msg { visitor.visit_expr(item); }
        }
        StmtKind::Import { names } => {
        for item in names.iter() { visitor.visit_alias(item); }
        }
        StmtKind::ImportFrom { names, .. } => {
        for item in names.iter() { visitor.visit_alias(item); }
        }
        StmtKind::Global { .. } => {

        }
        StmtKind::Nonlocal { .. } => {

        }
        StmtKind::Expr { value } => {
        visitor.visit_expr(value);
        }
        StmtKind::Pass => {

        }
        StmtKind::Break => {

        }
        StmtKind::Continue => {

        }
    }
}

pub fn walk_expr<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Expr) {
    match &node.kind {
        ExprKind::BoolOp { values, .. } => {
        for item in values.iter() { visitor.visit_expr(item); }
        }
        ExprKind::NamedExpr { target, value } => {
        visitor.visit_expr(target);
        visitor.visit_expr(value);
        }
        ExprKind::BinOp { left, right, .. } => {
        visitor.visit_expr(left);
        visitor.visit_expr(right);
        }
        ExprKind::UnaryOp { operand, .. } => {
        visitor.visit_expr(operand);
        }
        ExprKind::Lambda { args, body } => {
        visitor.visit_arguments(args);
        visitor.visit_expr(body);
        }
        ExprKind::IfExp { test, body, orelse } => {
        visitor.visit_expr(test);
        visitor.visit_expr(body);
        visitor.visit_expr(orelse);
        }
        ExprKind::Dict { keys, values } => {
        for item in keys.iter().flatten() { visitor.visit_expr(item); }
        for item in values.iter() { visitor.visit_expr(item); }
        }
        ExprKind::Set { elts } => {
        for item in elts.iter() { visitor.visit_expr(item); }
        }
        ExprKind::ListComp { elt, generators } => {
        visitor.visit_expr(elt);
        for item in generators.iter() { visitor.visit_comprehension(item); }
        }
        ExprKind::SetComp { elt, generators } => {
        visitor.visit_expr(elt);
        for item in generators.iter() { visitor.visit_comprehension(item); }
        }
        ExprKind::DictComp { key, value, generators } => {
        visitor.visit_expr(key);
        visitor.visit_expr(value);
        for item in generators.iter() { visitor.visit_comprehension(item); }
        }
        ExprKind::GeneratorExp { elt, generators } => {
        visitor.visit_expr(elt);
        for item in generators.iter() { visitor.visit_comprehension(item); }
        }
        ExprKind::Await { value } => {
        visitor.visit_expr(value);
        }
        ExprKind::Yield { value } => {
        if let Some(item) = value { visitor.visit_expr(item); }
        }
        ExprKind::YieldFrom { value } => {
        visitor.visit_expr(value);
        }
        ExprKind::Compare { left, comparators, .. } => {
        visitor.visit_expr(left);
        for item in comparators.iter() { visitor.visit_expr(item); }
        }
        ExprKind::Call { func, args, keywords } => {
        visitor.visit_expr(func);
        for item in args.iter() { visitor.visit_expr(item); }
        for item in keywords.iter() { visitor.visit_keyword(item); }
        }
        ExprKind::FormattedValue { value, format_spec, .. } => {
        visitor.visit_expr(value);
        if let Some(item) = format_spec { visitor.visit_expr(item); }
        }
        ExprKind::JoinedStr { values } => {
        for item in values.iter() { visitor.visit_expr(item); }
        }
        ExprKind::Constant { .. } => {

        }
        ExprKind::Attribute { value, .. } => {
        visitor.visit_expr(value);
        }
        ExprKind::Subscript { value, slice, .. } => {
        visitor.visit_expr(value);
        visitor.visit_expr(slice);
        }
        ExprKind::Starred { value, .. } => {
        visitor.visit_expr(value);
        }
        ExprKind::Name { .. } => {

        }
        ExprKind::List { elts, .. } => {
        for item in elts.iter() { visitor.visit_expr(item); }
        }
        ExprKind::Tuple { elts, .. } => {
        for item in elts.iter() { visitor.visit_expr(item); }
        }
        ExprKind::Slice { lower, upper, step } => {
        if let Some(item) = lower { visitor.visit_expr(item); }
        if let Some(item) = upper { visitor.visit_expr(item); }
        if let Some(item) = step { visitor.visit_expr(item); }
        }
    }
}

pub fn walk_pattern<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Pattern) {
    match &node.kind {
        PatternKind::MatchValue { value } => {
        visitor.visit_expr(value);
        }
        PatternKind::MatchSingleton { .. } => {

        }
        PatternKind::MatchSequence { patterns } => {
        for item in patterns.iter() { visitor.visit_pattern(item); }
        }
        PatternKind::MatchMapping { keys, patterns, .. } => {
        for item in keys.iter() { visitor.visit_expr(item); }
        for item in patterns.iter() { visitor.visit_pattern(item); }
        }
        PatternKind::MatchClass { cls, patterns, kwd_patterns, .. } => {
        visitor.visit_expr(cls);
        for item in patterns.iter() { visitor.visit_pattern(item); }
        for item in kwd_patterns.iter() { visitor.visit_pattern(item); }
        }
        PatternKind::MatchStar { .. } => {

        }
        PatternKind::MatchAs { pattern, .. } => {
        if let Some(item) = pattern { visitor.visit_pattern(item); }
        }
        PatternKind::MatchOr { patterns } => {
        for item in patterns.iter() { visitor.visit_pattern(item); }
        }
    }
}

pub fn walk_type_param<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a TypeParam) {
    match &node.kind {
        TypeParamKind::TypeVar { bound, .. } => {
        if let Some(item) = bound { visitor.visit_expr(item); }
        }
        TypeParamKind::ParamSpec { .. } => {

        }
        TypeParamKind::TypeVarTuple { .. } => {

        }
    }
}

pub fn walk_excepthandler<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a ExceptHandler) {
        if let Some(item) = &node.type_ { visitor.visit_expr(item); }
        for item in &node.body { visitor.visit_stmt(item); }
}

pub fn walk_arguments<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Arguments) {
        for item in &node.posonlyargs { visitor.visit_arg(item); }
        for item in &node.args { visitor.visit_arg(item); }
        if let Some(item) = &node.vararg { visitor.visit_arg(item); }
        for item in &node.kwonlyargs { visitor.visit_arg(item); }
        for item in node.kw_defaults.iter().flatten() { visitor.visit_expr(item); }
        if let Some(item) = &node.kwarg { visitor.visit_arg(item); }
        for item in &node.defaults { visitor.visit_expr(item); }
}

pub fn walk_arg<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Arg) {
        if let Some(item) = &node.annotation { visitor.visit_expr(item); }
}

pub fn walk_keyword<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Keyword) {
        visitor.visit_expr(&node.value);
}

pub fn walk_alias<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Alias) {
    let _ = (visitor, node);
}

pub fn walk_withitem<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a WithItem) {
        visitor.visit_expr(&node.context_expr);
        if let Some(item) = &node.optional_vars { visitor.visit_expr(item); }
}

pub fn walk_match_case<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a MatchCase) {
        visitor.visit_pattern(&node.pattern);
        if let Some(item) = &node.guard { visitor.visit_expr(item); }
        for item in &node.body { visitor.visit_stmt(item); }
}

pub fn walk_comprehension<'a, V: Visitor<'a>>(visitor: &mut V, node: &'a Comprehension) {
        visitor.visit_expr(&node.target);
        visitor.visit_expr(&node.iter);
        for item in &node.ifs { visitor.visit_expr(item); }
}

